# Generated by Django 4.2.30 on 2026-04-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "population",
                    models.IntegerField(help_text="ABS 2021 Census population"),
                ),
                (
                    "household_count",
                    models.IntegerField(help_text="ABS 2021 Census household count"),
                ),
                (
                    "median_income_index",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="1.00 = state average, 1.30 = 30% above average",
                        max_digits=6,
                    ),
                ),
                (
                    "growth_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual population growth rate percent",
                        max_digits=5,
                    ),
                ),
                (
                    "is_growth_corridor",
                    models.BooleanField(
                        default=False,
                        help_text="Designated growth corridor per Plan Melbourne 2017-2050",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("has_freeway_access", models.BooleanField(default=False)),
                (
                    "road_access_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        help_text="0-10 scale: proximity and quality of major road access",
                        max_digits=4,
                    ),
                ),
                (
                    "major_roads",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of nearby major roads/freeways",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "LGA",
                "verbose_name_plural": "LGAs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PetHospital",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("suburb", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency & Critical Care"),
                            ("specialist", "Specialist Referral"),
                            ("general", "General Practice Hospital"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "services",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list: Emergency,Surgery,Oncology,...",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LGAScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_pet_population", models.IntegerField(default=0)),
                (
                    "min_distance_to_hospital_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "pet_population_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "growth_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "supply_gap_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "road_access_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "affordability_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "composite_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("rank", models.IntegerField(default=0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "lga",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="pethosp.lga",
                    ),
                ),
                (
                    "nearest_hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nearest_to_lgas",
                        to="pethosp.pethospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-composite_score"],
            },
        ),
    ]
