"""
generate_report_pdf.py — Convert a plain-text investment/feasibility report
into a paginated, downloadable PDF.

Generic by design: works on any of this project's *_report.txt files without
modification (pethosp_report.txt, playcentre_report.txt, or future ones).

Usage:
    python3 generate_report_pdf.py playcentre_report.txt
    python3 generate_report_pdf.py                      # defaults to playcentre_report.txt
"""
import os
import sys
import textwrap

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Preformatted, Spacer
from reportlab.pdfgen import canvas

WRAP_WIDTH = 98  # chars per line before wrapping, tuned to fit A4 @ 8.5pt Courier


def wrap_report_lines(raw_lines):
    """Word-wrap long lines while preserving leading indentation as a hanging indent."""
    out = []
    for line in raw_lines:
        stripped = line.rstrip('\n')
        if len(stripped) <= WRAP_WIDTH:
            out.append(stripped if stripped else ' ')
            continue
        leading_ws = stripped[:len(stripped) - len(stripped.lstrip())]
        wrapped = textwrap.wrap(
            stripped,
            width=WRAP_WIDTH,
            initial_indent='',
            subsequent_indent=leading_ws + '  ',
            break_long_words=False,
            break_on_hyphens=False,
        )
        # Force-break any remaining over-length tokens (e.g. long unbroken URLs)
        # that word-wrap alone can't split, so nothing overflows the page width.
        fixed = []
        for wline in (wrapped if wrapped else [' ']):
            if len(wline) <= WRAP_WIDTH:
                fixed.append(wline)
                continue
            indent = wline[:len(wline) - len(wline.lstrip())]
            rest = wline[len(indent):]
            first = True
            while rest:
                avail = WRAP_WIDTH - len(indent) if first else WRAP_WIDTH - len(indent) - 2
                chunk, rest = rest[:avail], rest[avail:]
                fixed.append((indent if first else indent + '  ') + chunk)
                first = False
        out.extend(fixed)
    return out


def _add_page_number(pdf_canvas, doc):
    pdf_canvas.saveState()
    pdf_canvas.setFont('Helvetica', 8)
    pdf_canvas.setFillColorRGB(0.45, 0.45, 0.45)
    pdf_canvas.drawRightString(
        A4[0] - 18 * mm, 12 * mm, 'Page {}'.format(doc.page)
    )
    pdf_canvas.drawString(
        18 * mm, 12 * mm, 'Generated by Claude Code — investment analysis report'
    )
    pdf_canvas.restoreState()


def build_pdf(txt_path, pdf_path):
    with open(txt_path, 'r') as f:
        raw_lines = f.readlines()

    wrapped_lines = wrap_report_lines(raw_lines)
    body_text = '\n'.join(wrapped_lines)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        topMargin=16 * mm,
        bottomMargin=20 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        title=os.path.basename(txt_path),
    )

    mono_style = ParagraphStyle(
        name='ReportMono',
        fontName='Courier',
        fontSize=8.3,
        leading=10.2,
    )

    story = [
        Preformatted(body_text, mono_style),
        Spacer(1, 4 * mm),
    ]

    doc.build(story, onFirstPage=_add_page_number, onLaterPages=_add_page_number)


if __name__ == '__main__':
    src_name = sys.argv[1] if len(sys.argv) > 1 else 'playcentre_report.txt'
    base_dir = os.path.dirname(os.path.abspath(__file__))
    txt_path = os.path.join(base_dir, src_name)
    pdf_path = os.path.join(base_dir, os.path.splitext(src_name)[0] + '.pdf')

    if not os.path.exists(txt_path):
        print('Source report not found: {}'.format(txt_path))
        sys.exit(1)

    build_pdf(txt_path, pdf_path)
    print('Saved: {}'.format(pdf_path))
