# Generated by Django 4.2.30 on 2026-07-30 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Listing name or precinct name", max_length=200
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("industrial_land_sale", "Industrial Land For Sale"),
                            ("warehouse_lease", "Warehouse For Lease"),
                            ("commercial_dev_site", "Commercial Development Site"),
                            ("future_precinct", "Future Precinct / Town Centre"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "size_sqm",
                    models.IntegerField(
                        blank=True,
                        help_text="Floor/land size in sqm, if known",
                        null=True,
                    ),
                ),
                (
                    "price_or_rent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Price guide / rent, often a range or POA",
                        max_length=200,
                    ),
                ),
                (
                    "zoning_notes",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="True if listing detail was independently confirmed, False if source blocked verification",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["suburb__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorPlayCentre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("boutique_inflatable", "Boutique / Inflatable Play"),
                            ("big_box_chain", "Big-Box Chain Play Centre"),
                            ("trampoline_park", "Trampoline Park"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=25,
                    ),
                ),
                (
                    "services",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of offerings",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Suburb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "lga_name",
                    models.CharField(
                        help_text="Parent LGA, e.g. City of Wyndham", max_length=100
                    ),
                ),
                (
                    "population",
                    models.IntegerField(help_text="Approximate current population"),
                ),
                ("household_count", models.IntegerField()),
                (
                    "est_children_under_12",
                    models.IntegerField(
                        help_text="Estimated children aged 0-12, from household count x ABS-pattern child proportion"
                    ),
                ),
                (
                    "growth_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual population growth percent",
                        max_digits=5,
                    ),
                ),
                (
                    "is_growth_corridor",
                    models.BooleanField(
                        default=False,
                        help_text="Designated growth corridor per Plan Melbourne 2017-2050",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("has_freeway_access", models.BooleanField(default=False)),
                (
                    "road_access_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        help_text="0-10 scale: proximity and quality of major road access",
                        max_digits=4,
                    ),
                ),
                (
                    "major_roads",
                    models.CharField(blank=True, default="", max_length=300),
                ),
            ],
            options={
                "verbose_name": "Suburb",
                "verbose_name_plural": "Suburbs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SuburbScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_distance_to_competitor_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "family_population_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "growth_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "supply_gap_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "road_access_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "site_availability_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "composite_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("rank", models.IntegerField(default=0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "best_candidate_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_for_suburbs",
                        to="playcentre.candidatesite",
                    ),
                ),
                (
                    "nearest_competitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nearest_to_suburbs",
                        to="playcentre.competitorplaycentre",
                    ),
                ),
                (
                    "suburb",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="playcentre.suburb",
                    ),
                ),
            ],
            options={
                "ordering": ["-composite_score"],
            },
        ),
        migrations.AddField(
            model_name="competitorplaycentre",
            name="suburb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitors",
                to="playcentre.suburb",
            ),
        ),
        migrations.AddField(
            model_name="candidatesite",
            name="suburb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_sites",
                to="playcentre.suburb",
            ),
        ),
    ]
